[package]
name = "skrunkly_draw_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
# HTTP
axum = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

# Auth
jsonwebtoken = { version = "10", features = ["rust_crypto"] }

# Database
mongodb = { version = "3", features = ["snappy-compression"] }
futures-util = "0.3"

# Serde
serde = { version = "1", features = ["serde_derive"] }
toml = "1"

# Types
uuid = { version = "1", features = ["serde", "rng", "v4"] }
exn = "0.3"

# Logging
log = "0.4"
env_logger = "0.11.10"
chrono = { version = "0.4.44", features = ["serde"] }
serde_json = "1.0.149"

[profile.release]
lto = 'fat' # Perform link time optimizations for the whole dependency graph
codegen-units = 1 # Sacrifice compilation speed for a faster binary

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
