[package]
name = "skrunkly_draw_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
# HTTP
axum = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

# Auth
jsonwebtoken = { version = "10", features = ["rust_crypto"] }

# Serde
serde = { version = "1", features = ["serde_derive"] }
toml = "1"

# Types
uuid = { version = "1", features = ["serde", "rng", "v4"] }
exn = "0.3"

# Logging
log = "0.4"
env_logger = "0.11.10"
chrono = { version = "0.4.44", features = ["serde"] }

